import { createTranslator } from "next-intl";
import messages from "@/messages/en.json";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL || "https://bunshin3d.com";
const t = createTranslator({ locale: "en", messages, namespace: "SEO" });

export const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": `${APP_URL}/#organization`,
  name: t("organizationName"),
  alternateName: ["Bunshin", "Bunshin3D", "Bunshin AI", "Bunshin 3D Generator"],
  legalName: t("organizationName"),
  url: APP_URL,
  logo: {
    "@type": "ImageObject",
    url: `${APP_URL}/icon-512.png`,
    width: 512,
    height: 512,
    caption: t("organizationName"),
  },
  image: `${APP_URL}/og-image.jpg`,
  description: t("organizationDescription"),
  foundingDate: "2024",
  areaServed: "Worldwide",
  knowsAbout: [
    "AI 3D Model Generator",
    "Image to 3D Converter",
    "Photo to 3D Model",
    "Image to STL Converter",
    "PNG to STL Converter",
    "JPG to 3D Converter",
    "Logo to STL",
    "Logo to 3D Printing",
    "Drawing to 3D Model",
    "Sketch to 3D",
    "2D to 3D AI",
    "AI 3D Printing",
    "Free STL File Generator",
    "Free 3D Model Maker",
    "GLB File Generator",
    "OBJ File Generator",
    "FBX Export",
    "Unity 3D Asset Generator",
    "Unreal Engine Asset Generator",
    "Godot 3D Asset Generator",
    "Blender Mesh Generator",
    "Game Asset Generator",
    "3D Printing from Image",
    "AI 3D Modeling",
    "Neural 3D Reconstruction",
    "Computer Vision",
    "Depth Estimation",
    "Mesh Generation",
    "Watertight Mesh",
    "PBR Texturing",
    "STL File Format",
    "GLB File Format",
    "OBJ File Format",
    "FBX File Format",
    "glTF 2.0",
  ],
  knowsLanguage: ["en", "fr", "es", "de", "ja", "zh", "pt"],
  slogan: t("organizationSlogan"),
  sameAs: [
    "https://twitter.com/bunshin3d",
    "https://github.com/bunshin3d",
    "https://linkedin.com/company/bunshin3d",
  ],
  contactPoint: [
    {
      "@type": "ContactPoint",
      email: "support@bunshin3d.com",
      contactType: t("contactType"),
      availableLanguage: ["en", "fr", "es", "de", "ja", "zh", "pt"],
      areaServed: "Worldwide",
    },
  ],
  offers: {
    "@type": "AggregateOffer",
    priceCurrency: "EUR",
    lowPrice: "0",
    highPrice: "49.99",
    offerCount: "4",
  },
};
